<a href="https://colab.research.google.com/github/Nosckid/pytorch-self-study/blob/main/PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Section 1: PyTorch Fundamentals

#Table of Contents

## 1. Getting Started
  - Importing PyTorch
## 2. What is a Tensor?
  - The building block of everything
## 3. Random Tensors
  - Why randomness matters in AI
## 4. Zeros and Ones
  - Special tensors with purpose
## 5. Ranges & Tensor Types
  - Creating sequences and datatypes
## 6. Manipulating Tensors
  - Math with tensors, including matrix multiplication
## 7. Finding Values
  - Min, max, sum, and mean
## 8. Find Positions
  - Where is the min/max?
## 9. Reshaping & Rearranging
  - Bending tensors into new shapes
## 10. PyTorch & NumPy
  - Two tools, one team
## 11. Reproducibility
  - Taking the random out of random
## 12. Using a GPU
  - Making things much faster

## Lesson 1: Getting Started - Importing PyTorch

**What even is PyTorch?**

Imagine you want to build a robot that can recognize pictures of cats. To do that, the robots needs to do a lot of math - millions of calculations. **PyTorch** is a free tool that handles all that heavy math for you. It's one of the most popular tools used by AI engineers at companies like Meta, Tesla, and hospitals building medical AI.

Before you can use it, you have to **import** it - which just means telling Python: "*Hey, go grab the PyTorch toolbox so I can use it.*"

In [1]:
import torch              # This loads PyTorch
import numpy as np  # This loads NumPy (a math help tool)

print(torch.__version__) # This prints which version of PyTorch you have

2.10.0+cpu


## Lesson 2: What is a Tensor?

**The Big Idea**

A **tensor** is just a box that holds numbers. That's it.

Everything in AI - photos, sounds, medical scans, text - gets turned into numbers and stored inside tensors. PyTorch then does math on those numbers to find patterns.

Think of tensors like Lego. You start with one brick, then a row, then a flat plate, then a whole 3D structure. Each step adds a new **dimension**.

**The 4 Types of Tensors**

Here's a table showing all 4 types - from simplest to most complex.

<table style="font-family: sans-serif; font-size: 15px; border-collapse: separate; border-spacing: 0; width: 100%; max-width: 750px;">
  <thead>
    <tr style="background-color: #f0f4ff;">
      <th style="padding: 16px 22px; text-align: left; border-bottom: 2px solid #c5d0f5; color: #3a3aaa;">Name</th>
      <th style="padding: 16px 22px; text-align: left; border-bottom: 2px solid #c5d0f5; color: #3a3aaa;">What it is</th>
      <th style="padding: 16px 22px; text-align: left; border-bottom: 2px solid #c5d0f5; color: #3a3aaa;">Example</th>
      <th style="padding: 16px 22px; text-align: center; border-bottom: 2px solid #c5d0f5; color: #3a3aaa;">Dimensions</th>
    </tr>
  </thead>
  <tbody>
    <tr style="background-color: #ffffff;">
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;"><strong>Scalar</strong></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">One single number</td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;"><code>7</code></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee; text-align: center;">0</td>
    </tr>
    <tr style="background-color: #f9f9f9;">
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;"><strong>Vector</strong></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">A list of numbers</td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;"><code>[7, 7]</code></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee; text-align: center;">1</td>
    </tr>
    <tr style="background-color: #ffffff;">
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;"><strong>Matrix</strong></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">A grid of numbers (rows &amp; columns)</td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;"><code>[[7, 8], [9, 10]]</code></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee; text-align: center;">2</td>
    </tr>
    <tr style="background-color: #f9f9f9;">
      <td style="padding: 18px 22px;"><strong>Tensor</strong></td>
      <td style="padding: 18px 22px;">A cube of numbers (like a color photo)</td>
      <td style="padding: 18px 22px;"><code>[[[1,2,3],[3,6,9],[2,4,5]]]</code></td>
      <td style="padding: 18px 22px; text-align: center;">3+</td>
    </tr>
  </tbody>
</table>

### **Scalar - one single number**

A scalar is the simplest tensor. It holds exactly one number, nothing more

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

You can ask two questions about it:

In [3]:
print(f"Number of dimension: {scalar.ndim}")  # How many dimensions? Always 0 for a scalar
print(f"Item: {scalar.item()}")                            # Pulls out the plain number (useful for regular Python math)

Number of dimension: 0
Item: 7


why `.item()`? Sometimes you need the number as a regular Python number, not a tensor, useful for regular Python math. `.item()` does that conversion for you.

### **Vector - a list of numbers**

A vector is a straight line of numbers. Think of a row of lockers - each one holds a number. In healthcare AI, a vector might hold one patient's data: age, blood pressure, temperature - all in one line

In [4]:
vector = torch.tensor([7, 7])

print(f"Number of dimension: {vector.ndim}")    # 1 - It's a flat list
print(f"Shape of the tensor: {vector.shape}")  # torch.Size([2]) - there are 2 numbers

Number of dimension: 1
Shape of the tensor: torch.Size([2])


### **Matrix - a grid of numbers**

A matrix is like a spreadsheet with rows and coumns
> Convention: We write matrices in ALL CAPS (like `MATRIX`) so they're easy to spot in code. This is a common habit in machine learning.

In [5]:
MATRIX = torch.tensor([
    [7, 8],     # row 1
    [9, 10]    # row 2
])

print(f"Number  of dimension: {MATRIX.ndim}")              # 2 - two dimension
print(f"Number of shape{ {MATRIX.shape}}")                   # torch.Size([2, 2]) - 2 rows, 2 column
print(f"The first row: {MATRIX[0]}")                                  # tensor([7, 8]) - grabs row 1
print(f"Second column of the first row: {MATRIX[0, 1]}")  # 8 - grabs row 1, column 2

Number  of dimension: 2
Number of shape{torch.Size([2, 2])}
The first row: tensor([7, 8])
Second column of the first row: 8


### **Tensor - a cube of numbers (3+ dimensions)**

A true tensor has 3 or more dimensions. The best real-world example is a color photo:
- Dimension 1 -> height (rows of pixels)
- Dimension 2 -> width (collumns of pixels)
- Dimension 3 -> color channels (Red, Green, Blue = 3 channels)

In [6]:
TENSOR = torch.tensor([
    [
        [1, 2, 3],  # row 1
        [3, 6, 9],  # row 2
        [2, 4, 5]   # row 3
    ]
])

print(f"Number of dimension: {TENSOR.ndim}")  # 3
print(f"Number of shape: {TENSOR.shape}")       # torch.Size([1, 3, 3]) - 1 block, 3 rows, 3 columns
print(f"First block : {TENSOR[0]}")                     # grabs the first (and only) block - a 3x3 matrix

Number of dimension: 3
Number of shape: torch.Size([1, 3, 3])
First block : tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])


***The Full Picture - Everything in One Place**

<table style="font-family: sans-serif; font-size: 15px; border-collapse: separate; border-spacing: 0; width: 100%; max-width: 820px;">
  <thead>
    <tr style="background-color: #f0f4ff;">
      <th style="padding: 16px 22px; text-align: left; border-bottom: 2px solid #c5d0f5; color: #3a3aaa;">Variable</th>
      <th style="padding: 16px 22px; text-align: center; border-bottom: 2px solid #c5d0f5; color: #3a3aaa;">ndim</th>
      <th style="padding: 16px 22px; text-align: center; border-bottom: 2px solid #c5d0f5; color: #3a3aaa;">shape</th>
      <th style="padding: 16px 22px; text-align: left; border-bottom: 2px solid #c5d0f5; color: #3a3aaa;">Plain English</th>
    </tr>
  </thead>
  <tbody>
    <tr style="background-color: #ffffff;">
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;"><code>scalar</code></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee; text-align: center;">0</td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee; text-align: center;"><code>[]</code></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">One single number</td>
    </tr>
    <tr style="background-color: #f9f9f9;">
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;"><code>vector</code></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee; text-align: center;">1</td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee; text-align: center;"><code>[2]</code></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">A list of 2 numbers</td>
    </tr>
    <tr style="background-color: #ffffff;">
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;"><code>MATRIX</code></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee; text-align: center;">2</td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee; text-align: center;"><code>[2, 2]</code></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">2 rows, 2 columns</td>
    </tr>
    <tr style="background-color: #f9f9f9;">
      <td style="padding: 18px 22px;"><code>TENSOR</code></td>
      <td style="padding: 18px 22px; text-align: center;">3</td>
      <td style="padding: 18px 22px; text-align: center;"><code>[1, 3, 3]</code></td>
      <td style="padding: 18px 22px;">1 block, 3 rows, 3 columns</td>
    </tr>
  </tbody>
</table>

## Lesson 3: Random Tensors - Why AI Starts with Random Numbers

**First - Why Does AI Use Random Numbers At All?**

Let's say you're trying to teach a computer to recognize whether an X-ray shows a healthy lung or a sick one.

The computer needs to learn thousands of rules - things like *"if this region is darker than normal, that might mean fluid"*. But here's the problem: **nobody tells it those rules upfront**. It has to figure them out oon its own.

So how does it start? It starts by **guessing randomly**.

Imagine you're trying to tune a radio to find a station. You don't know where it is, so you spin the dial randomly, listen, adjust, spin again - until the sound get clearer. AI does the exact same thing:

1. Start with random numbers (random guesses)
2. Make a prediction
3. Check how wrong it was
4. Adjust the numbers slightly to be less wrong
5. Repeat millions of times until it's good

Those numbers it adjusts over and over are called **weights**, and they always start as random tensors.

In [7]:
# Creating a Random Tensor
random_tensor = torch.rand(size=(3, 4))
random_tensor

tensor([[0.4096, 0.1428, 0.5652, 0.1218],
        [0.1835, 0.3336, 0.7979, 0.3541],
        [0.2527, 0.1466, 0.5904, 0.5554]])

**Breaking down `torch.rand(size=(3, 4))` completely**

---
- `torch`: The PyTorch toolbox
- `.rand` : "Give me random numbers between 0.0 and 1.0"
- `size=(3, 4)` : Make a grid with 3 rows and 4 coumns.

*Why between 0 and 1 specifically?* Because small numbers are easier for the math inside AI to work with. Numbers between 0 and 1 don't explode into huge values when you multiply them togeether millions of times



**Checking What You Made**

In [8]:
print(f"Number of dimension (how many [] deep it goes): {random_tensor.ndim}")
print(f"Shape (exact size of each dimension): {random_tensor.shape}")
print(f"Data type (what kind of numbers are stored): {random_tensor.dtype}")
print(f"Total number of individual values store: {random_tensor.numel()}")

Number of dimension (how many [] deep it goes): 2
Shape (exact size of each dimension): torch.Size([3, 4])
Data type (what kind of numbers are stored): torch.float32
Total number of individual values store: 12


What each line means:
- `.ndim` -> **2** because we have rows AND columns - two layers of structure
- `.shape` -> **[3, 4]** - read left to right: 3 rows, 4 columns.
- `.dtype` -> **torch.flooat32** - decimal numbers using 32 bits of memory each. More bits = more precision = more memory. 32 is PyTorch's default sweet spot
- `.numel()` -> **12** - short for "number of elements". Just 3 x 4 = 12 numbers total

**Random Tensors That Look Like Images**

A color image - like an MRI scan - is stored as a 3D tensor:
* `224` -> Height (rows of pixel)
* `224` -> Width (columns of pixels)
* `3` -> Color channels (Red, Green, Blue)

In [9]:
# Create an image-like random tensor
random_image_tensor = torch.rand(size=(224, 224, 3))

In [10]:
print(f"Shape of image tensor: {random_image_tensor.shape}")
print(f"Number of dimension: {random_image_tensor.ndim}")
print(f"Height (rows): {random_image_tensor.shape[0]}")
print(f"Width (rows): {random_image_tensor.shape[1]}")
print(f"Color channels: {random_image_tensor.shape[2]}")
print(f"Total pixel values stored: {random_image_tensor.numel()}")

Shape of image tensor: torch.Size([224, 224, 3])
Number of dimension: 3
Height (rows): 224
Width (rows): 224
Color channels: 3
Total pixel values stored: 150528


## Lesson 4: Zeros and Ones

**Why do these exist?**

Two very common needs in AI:

- **Zeros** → "I need a blank tensor the same shape as this one" — used to hold results before you fill them in, or to block out parts of the data you want to ignore.

- **Ones** → "I need a tensor full of 1s" — used in math operations where multiplying by 1 leaves things unchanged, acting like a neutral starting point

Think of zeros like an empty spreadsheet waiting to be filled, and ones like a sheet pre-filled with 1s so multiplying anything by it keeps it the same.

**Zeros**

In [11]:
# Create a tensor filled with zeros - 3 rows, 4 columns
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

The `.` after each `0` (like `0.`) just means it's a decimal number (`float32`), not a whole number. It's PyTorch saying: "*I'm storing 0.0, not just 0.*"

**Real use case:** In AI, zeros are used as a **mask**  - a way to block out parts of a tensor you want to ignore. Imaine analyzing an MRI and telling the model: "*ignore everything outside the lung region*". You'd cover the rest with zeros.

In [12]:
# Multiplying anything by a zeros tensor wipes it out completely
some_tensor = torch.rand(size=(3, 4))
result = some_tensor * zeros
print(f"Result of multiplying by zeros:\n{result}")

Result of multiplying by zeros:
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


Multiplying anything by zero and it disappears - that's exactly the point

**Ones**

In [13]:
# Create a tensor filled with ones - 3 rows, 4 columns
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

**Real use case:** Ones are used when you need a **neutral starting point** - multiplying anything  by **1** leaves it unchanged. In AI, ones tensors are also used to initialize certain weights that shouldn't start at zero (because zero weights learn nothing).

In [14]:
# Multiplying anything by a ones tensor leaves it untouched
result = some_tensor * ones
result == some_tensor

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

**Inspecting Both**

In [15]:
# Check that zeros and ones have the same properties as any other tensor
print(f"Zeros dtype (number type): {zeros.dtype}")
print(f"Ones dtype (number type): {ones.dtype}")
print(f"Zeros shape: {zeros.shape}")
print(f"Ones shape: {ones.shape}")

Zeros dtype (number type): torch.float32
Ones dtype (number type): torch.float32
Zeros shape: torch.Size([3, 4])
Ones shape: torch.Size([3, 4])


Both are `float32` by default - same as `torch.rand`. They behave exactly like any other tensor, just with predictable values instead of random ones.

## Lesson 5: Ranges & Tensor Types



### Part 1 - Ranges

Sometimes you don't want random numbrs or all zeros. You want a clean sequence - like 0, 1, 2, 3, 4. That's what `torch.arange` does.

In [16]:
# Create a sequence of numbers from 0 up to  (but not inclusing) 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Breaking down** `torch.arange(start=0, end=10, step=1)`

---
- `start=0`: Begin counting from 0
- `end=10`: Stop before 10 - 10 is not included
- `step=1`: Jump by 1 each time

The `end` not being included is intentional - it's a Python-wide rule. Think of it like a race: you run to the finish line but you don't go past it.

You can change `step` to skip numbers:

In [17]:
# Count from 0 to 100, jumping by 10 each time
zero_to_hundred = torch.arange(start=0, end=100, step=10)
zero_to_hundred

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

**Tensors Like Other Tensors**

A very common need: "*I want a tensor the same shape as this other one, but filled with zeros.*" Instead of retyping the shape, PyTorch lets you copy it automatically:

In [18]:
# Create a zeros tensor with the exact same shape as zero_to_ten
# Useful when you need a blank version of an existing tensor
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

`zeros_like` reads the shape of `zero_to_ten` (which is `[10]`) and makes a zeros tensor of identical size. No need to count manually. There's also `torch.ones_like` that does the same but with ones.

### Part 2 - Tensor Data Types
This is one of the most important - and most confusing - parts of PyTorch. Pay close attention here because **mismatched data types cause more more errors than almost anything else.**

What is a data type?

Every number stored in a tensor has a **type** - it tells PyTorch hw much memory to use and how precise the number should be.

Think of it like cups of different sizes:
- A tiny cup holds less liquid but takes up less space on the table
- A large cup holds more liquid but takes up more space

Numbers work the same way - more bits = more precision, but more memory used.

---
**The Main Types You'll Use**

In [19]:
# float32 - PyTorch default. The everyday workhorse
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                                                  dtype=torch.float32)   # 32 bits per number

# float16 - Half the memory of float32. Used when training on GPUs to go faster
float_16_tensor = torch.tensor([3., 6., 9.],
                                                  dtype=torch.float16)  # 16 bits per number

# int32 - Whole numbers only. No decimals at all.
int_32_tensor = torch.tensor([3, 6, 9],
                                              dtype=torch.int32)   # whole numbers, 32 bits

In [20]:
# Always confirm what type your tensor actually is
print(f"Float32 tensor type: {float_32_tensor.dtype}")
print(f"Float16 tensor type: {float_16_tensor.dtype}")
print(f"int32 tensor type: {int_32_tensor.dtype}")

Float32 tensor type: torch.float32
Float16 tensor type: torch.float16
int32 tensor type: torch.int32


**The 3 Big Attributes - Device, dtype, shape**

Every tensor has three things you should always know about:

In [21]:
some_tensor = torch.rand(size=(3, 4))

# These three attributes answer the most common deebugging questions
print(f"Datatype (what kind of numbers): {some_tensor.dtype}")
print(f"Shape (size of each dimension): {some_tensor.shape}")
print(f"Device (where it lives): {some_tensor.device}")

Datatype (what kind of numbers): torch.float32
Shape (size of each dimension): torch.Size([3, 4])
Device (where it lives): cpu


**Device** is new. A tensor lives either on the **CPU** (your normal computer processor) or the **GPU** (a special chip built for fast math). We'll cover this properly in Lesson 12 - for now just know it exists.

---
**Why dtype Errors Happen - And How to Fix Them**

In [22]:
# float32 and float16 tensors cannot do math together directly
# This would crash: float_32_tensor + float_16_tensor

# Fix: Convert one tensor to match the other's type using .type()
float_32_converted = float_16_tensor.type(dtype=torch.float32)

# Now they match and can be added together
result = float_32_tensor + float_32_converted
print(f"Result after fixing dtype mismatch: {result}")

Result after fixing dtype mismatch: tensor([ 6., 12., 18.])


The rule is simple: **both tensors must be the same dtype before doing any math together**. When you see a dtype error, `.type(torch.float32)` is almost always the fix

<table style="font-family: sans-serif; font-size: 15px; border-collapse: separate; border-spacing: 0; width: 100%; max-width: 860px;">
  <thead>
    <tr style="background-color: #f0f4ff;">
      <th style="padding: 16px 22px; text-align: left; border-bottom: 2px solid #c5d0f5; color: #3a3aaa;">Concept</th>
      <th style="padding: 16px 22px; text-align: left; border-bottom: 2px solid #c5d0f5; color: #3a3aaa;">Code</th>
      <th style="padding: 16px 22px; text-align: left; border-bottom: 2px solid #c5d0f5; color: #3a3aaa;">What it does</th>
    </tr>
  </thead>
  <tbody>
    <tr style="background-color: #ffffff;">
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">Number sequence</td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;"><code>torch.arange(start, end, step)</code></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">Counts from start up to (not including) end</td>
    </tr>
    <tr style="background-color: #f9f9f9;">
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">Copy a shape with zeros</td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;"><code>torch.zeros_like(tensor)</code></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">Same shape as input, filled with 0s</td>
    </tr>
    <tr style="background-color: #ffffff;">
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">Default decimal type</td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;"><code>torch.float32</code></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">32-bit decimal — PyTorch's everyday default</td>
    </tr>
    <tr style="background-color: #f9f9f9;">
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">Fast GPU type</td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;"><code>torch.float16</code></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">16-bit decimal — half the memory, used for speed</td>
    </tr>
    <tr style="background-color: #ffffff;">
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">Fix a dtype mismatch</td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;"><code>tensor.type(torch.float32)</code></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">Converts tensor to a different number type</td>
    </tr>
    <tr style="background-color: #f9f9f9;">
      <td style="padding: 18px 22px;">Check all 3 key attributes</td>
      <td style="padding: 18px 22px;"><code>.dtype / .shape / .device</code></td>
      <td style="padding: 18px 22px;">Type, size, and where it lives (CPU or GPU)</td>
    </tr>
  </tbody>
</table>

## Lesson 6: Manipulating Tensors

**The Big Picture**

Everything an AI model does is just math on tensors - over and over, millions of times. There are two kinds of math:
* **Basic operation** -> add, subtract, multiply, divide (simple, element by element)

* **Matrix multiplication** -> the most important operatin in all of AI

Let's do both

### Part 1 - Basic Operations

These work exactly like regular math, just applied to every single number in the tensor at once.

In [23]:
# Start with a simple tensor
tensor = torch.tensor([1, 2, 3])
print(f"Original tensor: {tensor}")

Original tensor: tensor([1, 2, 3])


In [24]:
# Add 10 to every number in the tensor
print(f"Add 10 to each value: \n{tensor + 10}")

# Subtract 10 from every number
print(f"\nSubtract 10 from each value: \n{tensor - 10}")

# Multiply every number by 10
print(f"\nMultiply each value by 10: \n{tensor * 10}")

# Divide every number by 10
print(f"\nDivide each value by 10: \n{tensor / 10}")

Add 10 to each value: 
tensor([11, 12, 13])

Subtract 10 from each value: 
tensor([-9, -8, -7])

Multiply each value by 10: 
tensor([10, 20, 30])

Divide each value by 10: 
tensor([0.1000, 0.2000, 0.3000])


PyTorch applies the operation to  **every single number** in the tensor simultaneously. So `tensor + 10` doesn't add 10 once - it adds 10 to all 3 values at the same time.

---
**PyTorch Built-in Math Functions**

You can also use Pytorch's own named functions intead of symbols. They do the exact same thing - just written differently:

In [25]:
# torch.add() is the same as tensor + 10
print(f"Using torch.add(): \n{torch.add(tensor, 10)}")

# torch.mul() is the same as tensor * 10
print(f"\nUsing torch.mul(): \n{torch.mul(tensor, 10)} ")

# torch.sub() is the same as tensor - 10
print(f"\nUsing torch.sub(): \n{torch.sub(tensor, 10)}")

# torch.div() is the same as tensor / 10
print(f"\nUsing torch.div(): \n{torch.div(tensor, 10)}")

Using torch.add(): 
tensor([11, 12, 13])

Using torch.mul(): 
tensor([10, 20, 30]) 

Using torch.sub(): 
tensor([-9, -8, -7])

Using torch.div(): 
tensor([0.1000, 0.2000, 0.3000])


Why do both styles exist? The symbol style (`+`,`*`) is faster to write. The function style (`torch.add`) is more explicit and easier to read in complex code. You'll see both in real projects.

### Part 2 - Matrix Multiplication

This is the single mosr important operation in all of deep learning. Every AI prediction - whether it's diagnosing a disease or recognizing a face - comes down to matrix multiplication happening thousands of times per second.

**First - what does it actually do?**
Regular multiplication (element-wise) just matches numbers in the same position:

`[1., 2., 3.] * [1., 2., 3.] = [1, 4, 9]`
Positioon1 x Position1, Position2 x Position 2, and so on.

Matrix multiplication is different. Each output number is the **sum of a whole row multiplied against a whole column:**

`[1, 2, 3] · [1, 2, 3] = (1×1) + (2×2) + (3×3) = 1 + 4 + 9 = 14`

One single number - called a **dot product**- comes out of multiplying an entire row against an entire column.

---
**The One Rule That Trips Everyone Up - Shape Compatibility**

For matrix multiplication to work, the **number of columns in the first matrix must equal the number of rows in the second matrix.**

`Matrix A shape:  (3, 2)  ← 3 rows, 2 columns`

`Matrix B shape:  (2, 4)  ← 2 rows, 4 columns`

                                 ↑ ↑
                 These two must match
`Result shape:    (3, 4)  ← outer dimensions survive`

Think of it like a handshake - the inner numbers must be the same or there's nothing to multiply together.

In [29]:
# Create two tensors to multiply
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]]) # shape: (3, 2)

tensor_B = torch.tensor([[7, 8, 9, 10],
                                      [11, 12, 13, 14]])  # shape: (2, 4)

In [30]:
# Method 1: @ symbol - the shorthand for matrix multiplication
result = tensor_A @ tensor_B
print(f"Result using @:\n{result}")

Result using @:
tensor([[ 29,  32,  35,  38],
        [ 65,  72,  79,  86],
        [101, 112, 123, 134]])


In [31]:
# Method 2: torch.matmul() - same thing, more explicit name
result2 = torch.matmul(tensor_A, tensor_B)
print(f"Result using torch.matmul(): \n{result2}")

Result using torch.matmul(): 
tensor([[ 29,  32,  35,  38],
        [ 65,  72,  79,  86],
        [101, 112, 123, 134]])


In [34]:
# Compare both result and result2
if torch.equal(result, result2):
  print("They are the same")
else:
  print("They are different")

They are the same


In [35]:
# Confirm the output shape - outer dimensions survive
print(f"Shape of result {result.shape}")

Shape of result torch.Size([3, 4])


`@` and `torch.matmul()` do the exact same thing - `@` is just shorter to type. use whichever is clearer to you.