<a href="https://colab.research.google.com/github/Nosckid/pytorch-self-study/blob/main/PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Section 1: PyTorch Fundamentals

#Table of Contents

## 1. Getting Started
  - Importing PyTorch
## 2. What is a Tensor?
  - The building block of everything
## 3. Random Tensors
  - Why randomness matters in AI
## 4. Zeros and Ones
  - Special tensors with purpose
## 5. Ranges & Tensor Types
  - Creating sequences and datatypes
## 6. Manipulating Tensors
  - Math with tensors, including matrix multiplication
## 7. Finding Values
  - Min, max, sum, and mean
## 8. Find Positions
  - Where is the min/max?
## 9. Reshaping & Rearranging
  - Bending tensors into new shapes
## 10. PyTorch & NumPy
  - Two tools, one team
## 11. Reproducibility
  - Taking the random out of random
## 12. Using a GPU
  - Making things much faster

## Lesson 1: Getting Started - Importing PyTorch

**What even is PyTorch?**

Imagine you want to build a robot that can recognize pictures of cats. To do that, the robots needs to do a lot of math - millions of calculations. **PyTorch** is a free tool that handles all that heavy math for you. It's one of the most popular tools used by AI engineers at companies like Meta, Tesla, and hospitals building medical AI.

Before you can use it, you have to **import** it - which just means telling Python: "*Hey, go grab the PyTorch toolbox so I can use it.*"

In [1]:
import torch              # This loads PyTorch
import numpy as np  # This loads NumPy (a math help tool)

print(torch.__version__) # This prints which version of PyTorch you have

2.11.0+cpu


## Lesson 2: What is a Tensor?

**The Big Idea**

A **tensor** is just a box that holds numbers. That's it.

Everything in AI - photos, sounds, medical scans, text - gets turned into numbers and stored inside tensors. PyTorch then does math on those numbers to find patterns.

Think of tensors like Lego. You start with one brick, then a row, then a flat plate, then a whole 3D structure. Each step adds a new **dimension**.

**The 4 Types of Tensors**

Here's a table showing all 4 types - from simplest to most complex.

<table style="font-family: sans-serif; font-size: 15px; border-collapse: separate; border-spacing: 0; width: 100%; max-width: 750px;">
  <thead>
    <tr style="background-color: #f0f4ff;">
      <th style="padding: 16px 22px; text-align: left; border-bottom: 2px solid #c5d0f5; color: #3a3aaa;">Name</th>
      <th style="padding: 16px 22px; text-align: left; border-bottom: 2px solid #c5d0f5; color: #3a3aaa;">What it is</th>
      <th style="padding: 16px 22px; text-align: left; border-bottom: 2px solid #c5d0f5; color: #3a3aaa;">Example</th>
      <th style="padding: 16px 22px; text-align: center; border-bottom: 2px solid #c5d0f5; color: #3a3aaa;">Dimensions</th>
    </tr>
  </thead>
  <tbody>
    <tr style="background-color: #ffffff;">
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;"><strong>Scalar</strong></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">One single number</td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;"><code>7</code></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee; text-align: center;">0</td>
    </tr>
    <tr style="background-color: #f9f9f9;">
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;"><strong>Vector</strong></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">A list of numbers</td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;"><code>[7, 7]</code></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee; text-align: center;">1</td>
    </tr>
    <tr style="background-color: #ffffff;">
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;"><strong>Matrix</strong></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">A grid of numbers (rows &amp; columns)</td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;"><code>[[7, 8], [9, 10]]</code></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee; text-align: center;">2</td>
    </tr>
    <tr style="background-color: #f9f9f9;">
      <td style="padding: 18px 22px;"><strong>Tensor</strong></td>
      <td style="padding: 18px 22px;">A cube of numbers (like a color photo)</td>
      <td style="padding: 18px 22px;"><code>[[[1,2,3],[3,6,9],[2,4,5]]]</code></td>
      <td style="padding: 18px 22px; text-align: center;">3+</td>
    </tr>
  </tbody>
</table>

### **Scalar - one single number**

A scalar is the simplest tensor. It holds exactly one number, nothing more

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

You can ask two questions about it:

In [3]:
print(f"Number of dimension: {scalar.ndim}")  # How many dimensions? Always 0 for a scalar
print(f"Item: {scalar.item()}")                            # Pulls out the plain number (useful for regular Python math)

Number of dimension: 0
Item: 7


why `.item()`? Sometimes you need the number as a regular Python number, not a tensor, useful for regular Python math. `.item()` does that conversion for you.

### **Vector - a list of numbers**

A vector is a straight line of numbers. Think of a row of lockers - each one holds a number. In healthcare AI, a vector might hold one patient's data: age, blood pressure, temperature - all in one line

In [4]:
vector = torch.tensor([7, 7])

print(f"Number of dimension: {vector.ndim}")    # 1 - It's a flat list
print(f"Shape of the tensor: {vector.shape}")  # torch.Size([2]) - there are 2 numbers

Number of dimension: 1
Shape of the tensor: torch.Size([2])


### **Matrix - a grid of numbers**

A matrix is like a spreadsheet with rows and coumns
> Convention: We write matrices in ALL CAPS (like `MATRIX`) so they're easy to spot in code. This is a common habit in machine learning.

In [5]:
MATRIX = torch.tensor([
    [7, 8],     # row 1
    [9, 10]    # row 2
])

print(f"Number  of dimension: {MATRIX.ndim}")              # 2 - two dimension
print(f"Number of shape{ {MATRIX.shape}}")                   # torch.Size([2, 2]) - 2 rows, 2 column
print(f"The first row: {MATRIX[0]}")                                  # tensor([7, 8]) - grabs row 1
print(f"Second column of the first row: {MATRIX[0, 1]}")  # 8 - grabs row 1, column 2

Number  of dimension: 2
Number of shape{torch.Size([2, 2])}
The first row: tensor([7, 8])
Second column of the first row: 8


### **Tensor - a cube of numbers (3+ dimensions)**

A true tensor has 3 or more dimensions. The best real-world example is a color photo:
- Dimension 1 -> height (rows of pixels)
- Dimension 2 -> width (collumns of pixels)
- Dimension 3 -> color channels (Red, Green, Blue = 3 channels)

In [6]:
TENSOR = torch.tensor([
    [
        [1, 2, 3],  # row 1
        [3, 6, 9],  # row 2
        [2, 4, 5]   # row 3
    ]
])

print(f"Number of dimension: {TENSOR.ndim}")  # 3
print(f"Number of shape: {TENSOR.shape}")       # torch.Size([1, 3, 3]) - 1 block, 3 rows, 3 columns
print(f"First block : {TENSOR[0]}")                     # grabs the first (and only) block - a 3x3 matrix

Number of dimension: 3
Number of shape: torch.Size([1, 3, 3])
First block : tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])


***The Full Picture - Everything in One Place**

<table style="font-family: sans-serif; font-size: 15px; border-collapse: separate; border-spacing: 0; width: 100%; max-width: 820px;">
  <thead>
    <tr style="background-color: #f0f4ff;">
      <th style="padding: 16px 22px; text-align: left; border-bottom: 2px solid #c5d0f5; color: #3a3aaa;">Variable</th>
      <th style="padding: 16px 22px; text-align: center; border-bottom: 2px solid #c5d0f5; color: #3a3aaa;">ndim</th>
      <th style="padding: 16px 22px; text-align: center; border-bottom: 2px solid #c5d0f5; color: #3a3aaa;">shape</th>
      <th style="padding: 16px 22px; text-align: left; border-bottom: 2px solid #c5d0f5; color: #3a3aaa;">Plain English</th>
    </tr>
  </thead>
  <tbody>
    <tr style="background-color: #ffffff;">
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;"><code>scalar</code></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee; text-align: center;">0</td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee; text-align: center;"><code>[]</code></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">One single number</td>
    </tr>
    <tr style="background-color: #f9f9f9;">
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;"><code>vector</code></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee; text-align: center;">1</td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee; text-align: center;"><code>[2]</code></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">A list of 2 numbers</td>
    </tr>
    <tr style="background-color: #ffffff;">
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;"><code>MATRIX</code></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee; text-align: center;">2</td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee; text-align: center;"><code>[2, 2]</code></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">2 rows, 2 columns</td>
    </tr>
    <tr style="background-color: #f9f9f9;">
      <td style="padding: 18px 22px;"><code>TENSOR</code></td>
      <td style="padding: 18px 22px; text-align: center;">3</td>
      <td style="padding: 18px 22px; text-align: center;"><code>[1, 3, 3]</code></td>
      <td style="padding: 18px 22px;">1 block, 3 rows, 3 columns</td>
    </tr>
  </tbody>
</table>

## Lesson 3: Random Tensors - Why AI Starts with Random Numbers

**First - Why Does AI Use Random Numbers At All?**

Let's say you're trying to teach a computer to recognize whether an X-ray shows a healthy lung or a sick one.

The computer needs to learn thousands of rules - things like *"if this region is darker than normal, that might mean fluid"*. But here's the problem: **nobody tells it those rules upfront**. It has to figure them out oon its own.

So how does it start? It starts by **guessing randomly**.

Imagine you're trying to tune a radio to find a station. You don't know where it is, so you spin the dial randomly, listen, adjust, spin again - until the sound get clearer. AI does the exact same thing:

1. Start with random numbers (random guesses)
2. Make a prediction
3. Check how wrong it was
4. Adjust the numbers slightly to be less wrong
5. Repeat millions of times until it's good

Those numbers it adjusts over and over are called **weights**, and they always start as random tensors.

In [7]:
# Creating a Random Tensor
random_tensor = torch.rand(size=(3, 4))
random_tensor

tensor([[0.5824, 0.1455, 0.1746, 0.5379],
        [0.7022, 0.6780, 0.9002, 0.9693],
        [0.8620, 0.8035, 0.7789, 0.9250]])

**Breaking down `torch.rand(size=(3, 4))` completely**

---
- `torch`: The PyTorch toolbox
- `.rand` : "Give me random numbers between 0.0 and 1.0"
- `size=(3, 4)` : Make a grid with 3 rows and 4 coumns.

*Why between 0 and 1 specifically?* Because small numbers are easier for the math inside AI to work with. Numbers between 0 and 1 don't explode into huge values when you multiply them togeether millions of times



**Checking What You Made**

In [8]:
print(f"Number of dimension (how many [] deep it goes): {random_tensor.ndim}")
print(f"Shape (exact size of each dimension): {random_tensor.shape}")
print(f"Data type (what kind of numbers are stored): {random_tensor.dtype}")
print(f"Total number of individual values store: {random_tensor.numel()}")

Number of dimension (how many [] deep it goes): 2
Shape (exact size of each dimension): torch.Size([3, 4])
Data type (what kind of numbers are stored): torch.float32
Total number of individual values store: 12


What each line means:
- `.ndim` -> **2** because we have rows AND columns - two layers of structure
- `.shape` -> **[3, 4]** - read left to right: 3 rows, 4 columns.
- `.dtype` -> **torch.flooat32** - decimal numbers using 32 bits of memory each. More bits = more precision = more memory. 32 is PyTorch's default sweet spot
- `.numel()` -> **12** - short for "number of elements". Just 3 x 4 = 12 numbers total

**Random Tensors That Look Like Images**

A color image - like an MRI scan - is stored as a 3D tensor:
* `224` -> Height (rows of pixel)
* `224` -> Width (columns of pixels)
* `3` -> Color channels (Red, Green, Blue)

In [9]:
# Create an image-like random tensor
random_image_tensor = torch.rand(size=(224, 224, 3))

In [10]:
print(f"Shape of image tensor: {random_image_tensor.shape}")
print(f"Number of dimension: {random_image_tensor.ndim}")
print(f"Height (rows): {random_image_tensor.shape[0]}")
print(f"Width (rows): {random_image_tensor.shape[1]}")
print(f"Color channels: {random_image_tensor.shape[2]}")
print(f"Total pixel values stored: {random_image_tensor.numel()}")

Shape of image tensor: torch.Size([224, 224, 3])
Number of dimension: 3
Height (rows): 224
Width (rows): 224
Color channels: 3
Total pixel values stored: 150528


## Lesson 4: Zeros and Ones

**Why do these exist?**

Two very common needs in AI:

- **Zeros** → "I need a blank tensor the same shape as this one" — used to hold results before you fill them in, or to block out parts of the data you want to ignore.

- **Ones** → "I need a tensor full of 1s" — used in math operations where multiplying by 1 leaves things unchanged, acting like a neutral starting point

Think of zeros like an empty spreadsheet waiting to be filled, and ones like a sheet pre-filled with 1s so multiplying anything by it keeps it the same.

**Zeros**

In [11]:
# Create a tensor filled with zeros - 3 rows, 4 columns
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

The `.` after each `0` (like `0.`) just means it's a decimal number (`float32`), not a whole number. It's PyTorch saying: "*I'm storing 0.0, not just 0.*"

**Real use case:** In AI, zeros are used as a **mask**  - a way to block out parts of a tensor you want to ignore. Imaine analyzing an MRI and telling the model: "*ignore everything outside the lung region*". You'd cover the rest with zeros.

In [12]:
# Multiplying anything by a zeros tensor wipes it out completely
some_tensor = torch.rand(size=(3, 4))
result = some_tensor * zeros
print(f"Result of multiplying by zeros:\n{result}")

Result of multiplying by zeros:
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


Multiplying anything by zero and it disappears - that's exactly the point

**Ones**

In [13]:
# Create a tensor filled with ones - 3 rows, 4 columns
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

**Real use case:** Ones are used when you need a **neutral starting point** - multiplying anything  by **1** leaves it unchanged. In AI, ones tensors are also used to initialize certain weights that shouldn't start at zero (because zero weights learn nothing).

In [14]:
# Multiplying anything by a ones tensor leaves it untouched
result = some_tensor * ones
result == some_tensor

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

**Inspecting Both**

In [15]:
# Check that zeros and ones have the same properties as any other tensor
print(f"Zeros dtype (number type): {zeros.dtype}")
print(f"Ones dtype (number type): {ones.dtype}")
print(f"Zeros shape: {zeros.shape}")
print(f"Ones shape: {ones.shape}")

Zeros dtype (number type): torch.float32
Ones dtype (number type): torch.float32
Zeros shape: torch.Size([3, 4])
Ones shape: torch.Size([3, 4])


Both are `float32` by default - same as `torch.rand`. They behave exactly like any other tensor, just with predictable values instead of random ones.

## Lesson 5: Ranges & Tensor Types



### Part 1 - Ranges

Sometimes you don't want random numbrs or all zeros. You want a clean sequence - like 0, 1, 2, 3, 4. That's what `torch.arange` does.

In [16]:
# Create a sequence of numbers from 0 up to  (but not inclusing) 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Breaking down** `torch.arange(start=0, end=10, step=1)`

---
- `start=0`: Begin counting from 0
- `end=10`: Stop before 10 - 10 is not included
- `step=1`: Jump by 1 each time

The `end` not being included is intentional - it's a Python-wide rule. Think of it like a race: you run to the finish line but you don't go past it.

You can change `step` to skip numbers:

In [17]:
# Count from 0 to 100, jumping by 10 each time
zero_to_hundred = torch.arange(start=0, end=100, step=10)
zero_to_hundred

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

**Tensors Like Other Tensors**

A very common need: "*I want a tensor the same shape as this other one, but filled with zeros.*" Instead of retyping the shape, PyTorch lets you copy it automatically:

In [18]:
# Create a zeros tensor with the exact same shape as zero_to_ten
# Useful when you need a blank version of an existing tensor
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

`zeros_like` reads the shape of `zero_to_ten` (which is `[10]`) and makes a zeros tensor of identical size. No need to count manually. There's also `torch.ones_like` that does the same but with ones.

### Part 2 - Tensor Data Types
This is one of the most important - and most confusing - parts of PyTorch. Pay close attention here because **mismatched data types cause more more errors than almost anything else.**

What is a data type?

Every number stored in a tensor has a **type** - it tells PyTorch hw much memory to use and how precise the number should be.

Think of it like cups of different sizes:
- A tiny cup holds less liquid but takes up less space on the table
- A large cup holds more liquid but takes up more space

Numbers work the same way - more bits = more precision, but more memory used.

---
**The Main Types You'll Use**

In [19]:
# float32 - PyTorch default. The everyday workhorse
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                                                  dtype=torch.float32)   # 32 bits per number

# float16 - Half the memory of float32. Used when training on GPUs to go faster
float_16_tensor = torch.tensor([3., 6., 9.],
                                                  dtype=torch.float16)  # 16 bits per number

# int32 - Whole numbers only. No decimals at all.
int_32_tensor = torch.tensor([3, 6, 9],
                                              dtype=torch.int32)   # whole numbers, 32 bits

In [20]:
# Always confirm what type your tensor actually is
print(f"Float32 tensor type: {float_32_tensor.dtype}")
print(f"Float16 tensor type: {float_16_tensor.dtype}")
print(f"int32 tensor type: {int_32_tensor.dtype}")

Float32 tensor type: torch.float32
Float16 tensor type: torch.float16
int32 tensor type: torch.int32


**The 3 Big Attributes - Device, dtype, shape**

Every tensor has three things you should always know about:

In [21]:
some_tensor = torch.rand(size=(3, 4))

# These three attributes answer the most common deebugging questions
print(f"Datatype (what kind of numbers): {some_tensor.dtype}")
print(f"Shape (size of each dimension): {some_tensor.shape}")
print(f"Device (where it lives): {some_tensor.device}")

Datatype (what kind of numbers): torch.float32
Shape (size of each dimension): torch.Size([3, 4])
Device (where it lives): cpu


**Device** is new. A tensor lives either on the **CPU** (your normal computer processor) or the **GPU** (a special chip built for fast math). We'll cover this properly in Lesson 12 - for now just know it exists.

---
**Why dtype Errors Happen - And How to Fix Them**

In [22]:
# float32 and float16 tensors cannot do math together directly
# This would crash: float_32_tensor + float_16_tensor

# Fix: Convert one tensor to match the other's type using .type()
float_32_converted = float_16_tensor.type(dtype=torch.float32)

# Now they match and can be added together
result = float_32_tensor + float_32_converted
print(f"Result after fixing dtype mismatch: {result}")

Result after fixing dtype mismatch: tensor([ 6., 12., 18.])


The rule is simple: **both tensors must be the same dtype before doing any math together**. When you see a dtype error, `.type(torch.float32)` is almost always the fix

<table style="font-family: sans-serif; font-size: 15px; border-collapse: separate; border-spacing: 0; width: 100%; max-width: 860px;">
  <thead>
    <tr style="background-color: #f0f4ff;">
      <th style="padding: 16px 22px; text-align: left; border-bottom: 2px solid #c5d0f5; color: #3a3aaa;">Concept</th>
      <th style="padding: 16px 22px; text-align: left; border-bottom: 2px solid #c5d0f5; color: #3a3aaa;">Code</th>
      <th style="padding: 16px 22px; text-align: left; border-bottom: 2px solid #c5d0f5; color: #3a3aaa;">What it does</th>
    </tr>
  </thead>
  <tbody>
    <tr style="background-color: #ffffff;">
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">Number sequence</td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;"><code>torch.arange(start, end, step)</code></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">Counts from start up to (not including) end</td>
    </tr>
    <tr style="background-color: #f9f9f9;">
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">Copy a shape with zeros</td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;"><code>torch.zeros_like(tensor)</code></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">Same shape as input, filled with 0s</td>
    </tr>
    <tr style="background-color: #ffffff;">
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">Default decimal type</td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;"><code>torch.float32</code></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">32-bit decimal — PyTorch's everyday default</td>
    </tr>
    <tr style="background-color: #f9f9f9;">
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">Fast GPU type</td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;"><code>torch.float16</code></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">16-bit decimal — half the memory, used for speed</td>
    </tr>
    <tr style="background-color: #ffffff;">
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">Fix a dtype mismatch</td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;"><code>tensor.type(torch.float32)</code></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">Converts tensor to a different number type</td>
    </tr>
    <tr style="background-color: #f9f9f9;">
      <td style="padding: 18px 22px;">Check all 3 key attributes</td>
      <td style="padding: 18px 22px;"><code>.dtype / .shape / .device</code></td>
      <td style="padding: 18px 22px;">Type, size, and where it lives (CPU or GPU)</td>
    </tr>
  </tbody>
</table>

## Lesson 6: Manipulating Tensors

**The Big Picture**

Everything an AI model does is just math on tensors - over and over, millions of times. There are two kinds of math:
* **Basic operation** -> add, subtract, multiply, divide (simple, element by element)

* **Matrix multiplication** -> the most important operatin in all of AI

Let's do both

### Part 1 - Basic Operations

These work exactly like regular math, just applied to every single number in the tensor at once.

In [23]:
# Start with a simple tensor
tensor = torch.tensor([1, 2, 3])
print(f"Original tensor: {tensor}")

Original tensor: tensor([1, 2, 3])


In [24]:
# Add 10 to every number in the tensor
print(f"Add 10 to each value: \n{tensor + 10}")

# Subtract 10 from every number
print(f"\nSubtract 10 from each value: \n{tensor - 10}")

# Multiply every number by 10
print(f"\nMultiply each value by 10: \n{tensor * 10}")

# Divide every number by 10
print(f"\nDivide each value by 10: \n{tensor / 10}")

Add 10 to each value: 
tensor([11, 12, 13])

Subtract 10 from each value: 
tensor([-9, -8, -7])

Multiply each value by 10: 
tensor([10, 20, 30])

Divide each value by 10: 
tensor([0.1000, 0.2000, 0.3000])


PyTorch applies the operation to  **every single number** in the tensor simultaneously. So `tensor + 10` doesn't add 10 once - it adds 10 to all 3 values at the same time.

---
**PyTorch Built-in Math Functions**

You can also use Pytorch's own named functions intead of symbols. They do the exact same thing - just written differently:

In [25]:
# torch.add() is the same as tensor + 10
print(f"Using torch.add(): \n{torch.add(tensor, 10)}")

# torch.mul() is the same as tensor * 10
print(f"\nUsing torch.mul(): \n{torch.mul(tensor, 10)} ")

# torch.sub() is the same as tensor - 10
print(f"\nUsing torch.sub(): \n{torch.sub(tensor, 10)}")

# torch.div() is the same as tensor / 10
print(f"\nUsing torch.div(): \n{torch.div(tensor, 10)}")

Using torch.add(): 
tensor([11, 12, 13])

Using torch.mul(): 
tensor([10, 20, 30]) 

Using torch.sub(): 
tensor([-9, -8, -7])

Using torch.div(): 
tensor([0.1000, 0.2000, 0.3000])


Why do both styles exist? The symbol style (`+`,`*`) is faster to write. The function style (`torch.add`) is more explicit and easier to read in complex code. You'll see both in real projects.

### Part 2 - Matrix Multiplication

This is the single mosr important operation in all of deep learning. Every AI prediction - whether it's diagnosing a disease or recognizing a face - comes down to matrix multiplication happening thousands of times per second.

**First - what does it actually do?**
Regular multiplication (element-wise) just matches numbers in the same position:

`[1., 2., 3.] * [1., 2., 3.] = [1, 4, 9]`
Positioon1 x Position1, Position2 x Position 2, and so on.

Matrix multiplication is different. Each output number is the **sum of a whole row multiplied against a whole column:**

`[1, 2, 3] · [1, 2, 3] = (1×1) + (2×2) + (3×3) = 1 + 4 + 9 = 14`

One single number - called a **dot product**- comes out of multiplying an entire row against an entire column.

---
**The One Rule That Trips Everyone Up - Shape Compatibility**

For matrix multiplication to work, the **number of columns in the first matrix must equal the number of rows in the second matrix.**

`Matrix A shape:  (3, 2)  ← 3 rows, 2 columns`

`Matrix B shape:  (2, 4)  ← 2 rows, 4 columns`

                                 ↑ ↑
                 These two must match
`Result shape:    (3, 4)  ← outer dimensions survive`

Think of it like a handshake - the inner numbers must be the same or there's nothing to multiply together.

In [26]:
# Create two tensors to multiply
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]]) # shape: (3, 2)

tensor_B = torch.tensor([[7, 8, 9, 10],
                                      [11, 12, 13, 14]])  # shape: (2, 4)

In [27]:
# Method 1: @ symbol - the shorthand for matrix multiplication
result = tensor_A @ tensor_B
print(f"Result using @:\n{result}")

Result using @:
tensor([[ 29,  32,  35,  38],
        [ 65,  72,  79,  86],
        [101, 112, 123, 134]])


In [28]:
# Method 2: torch.matmul() - same thing, more explicit name
result2 = torch.matmul(tensor_A, tensor_B)
print(f"Result using torch.matmul(): \n{result2}")

Result using torch.matmul(): 
tensor([[ 29,  32,  35,  38],
        [ 65,  72,  79,  86],
        [101, 112, 123, 134]])


In [29]:
# Compare both result and result2
if torch.equal(result, result2):
  print("They are the same")
else:
  print("They are different")

They are the same


In [30]:
# Confirm the output shape - outer dimensions survive
print(f"Shape of result {result.shape}")

Shape of result torch.Size([3, 4])


`@` and `torch.matmul()` do the exact same thing - `@` is just shorter to type. use whichever is clearer to you.

---
**The Most Common Error - And the Fix**



In [31]:
# This will CRASH — inner dimensions don't match
# tensor_A is (3, 2) and tensor_B is (2, 4) — that works
# But if we flip B, it becomes (4, 2) — now 2 ≠ 4 and it breaks

# Fix: use .T to transpose (flip rows and columns)
tensor_B_wrong = torch.tensor([[7, 11],
                                                     [8, 12],
                                                     [9, 13],
                                                     [10, 14]])   # shape: (4, 2) - won't work with (3, 2)

# .T swaps rows ↔ columns, turning (4, 2) into (2, 4)
print(f"Orginal shape: \n{tensor_B_wrong.shape}")
print(f"\nTransposed shape:\n{tensor_B_wrong.T.shape}")

Orginal shape: 
torch.Size([4, 2])

Transposed shape:
torch.Size([2, 4])


In [32]:
# Now it works
result3 = tensor_A @ tensor_B_wrong.T
print(f"Result after transposing:\n{result3}")

Result after transposing:
tensor([[ 29,  32,  35,  38],
        [ 65,  72,  79,  86],
        [101, 112, 123, 134]])


`.T` literally flips the matrix - rows become columns and columns become rows. It's the standard fix whenever you get a shape mismatch error during matrix multiplication.

<table style="font-family: sans-serif; font-size: 15px; border-collapse: separate; border-spacing: 0; width: 100%; max-width: 860px;">
  <thead>
    <tr style="background-color: #f0f4ff;">
      <th style="padding: 16px 22px; text-align: left; border-bottom: 2px solid #c5d0f5; color: #3a3aaa;">Operation</th>
      <th style="padding: 16px 22px; text-align: left; border-bottom: 2px solid #c5d0f5; color: #3a3aaa;">Code</th>
      <th style="padding: 16px 22px; text-align: left; border-bottom: 2px solid #c5d0f5; color: #3a3aaa;">What it does</th>
    </tr>
  </thead>
  <tbody>
    <tr style="background-color: #ffffff;">
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">Add / Subtract / Multiply / Divide</td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;"><code>tensor + 10</code>, <code>tensor * 10</code></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">Applies to every single number in the tensor</td>
    </tr>
    <tr style="background-color: #f9f9f9;">
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">Same using functions</td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;"><code>torch.add()</code>, <code>torch.mul()</code></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">Identical result, more readable in complex code</td>
    </tr>
    <tr style="background-color: #ffffff;">
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">Matrix multiplication</td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;"><code>tensor_A @ tensor_B</code></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">Rows × columns — the core operation of all AI</td>
    </tr>
    <tr style="background-color: #f9f9f9;">
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">Same using function</td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;"><code>torch.matmul(A, B)</code></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">Identical to @, just more explicit</td>
    </tr>
    <tr style="background-color: #ffffff;">
      <td style="padding: 18px 22px;">Fix a shape mismatch</td>
      <td style="padding: 18px 22px;"><code>tensor.T</code></td>
      <td style="padding: 18px 22px;">Flips rows ↔ columns to make inner dimensions match</td>
    </tr>
  </tbody>
</table>

## Lesson 7: Finding Values - Min, Max, Sum & Mean

**Why Do These Matter?**

Once your AI model has done its math and produced a tensor full of numbers, you constantly need to ask questions like:
* What's the **highest** value? (Which class did the model predict the most confidently?)
* What's the **lowest** value? (What's the weakest signal?)
* What's the **total**? (How much loss accumulated?)
* What's the **average**? (What's the overall performance?)

These four operations answer those questions.

In [33]:
# Create a simple range of numbers to practice on
tensor = torch.arange(start=0, end=100, step=10)

print(f"Our tensor: \n{tensor}")
print(f"\nShape: \n{tensor.shape}")
print(f"\nDtype: \n{tensor.dtype}")

Our tensor: 
tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

Shape: 
torch.Size([10])

Dtype: 
torch.int64


`torch.int64` appears here instead of `float32` because `torch.arange` produces whole numbers - there are no decimals in `0, 10, 20,...`. Some PyTorch operations (like `mean`) require decimals, so we'll handle that below.

In [34]:
# MIN - find the smallest number in the entire tensore
print(f"Minimum value: {tensor.min()}")

# MAX - find the largest number in the entire tensor
print(f"\nMaximum value: {tensor.max()}")

# SUM - add every number together
print(f"\nSum of all values: {tensor.sum()}")

# MEAN - the average (requires float, so we convert first)
# int64 cannot compute mean - PyTorch will crash without the conversion
print(f"\nMean (average) value: {tensor.type(torch.float32).mean()}")

Minimum value: 0

Maximum value: 90

Sum of all values: 450

Mean (average) value: 45.0


**Why does `mean()` need `.type(torch.float32)` first?**

The mean of `[0, 10, 20, ...]` is `45.0` - a decimal. But our tensor stores `int64` (whole nmubers only), which can't hold decimals. If you try `tensor.mean()`  on an int64 tensor, PyTorch throws an error because it can't store the decimal result.

The fix: `.type(torch.float32)` converts the tensor to decimal first, then `.mean()` works perfectly.


---
**Two Ways To Call Theses Functions**

PyTorch gives you two styles - both produce identical results:

In [35]:
# Style 1: call directly on the tensor (like a method)
print(("Method Style"))
print(f"\nMin (method style): {tensor.min()}")
print(f"Max (method style): {tensor.max()}")
print(f"Sum (method style): {tensor.sum()}")

# Style 2: call via torch (like a standalone function)
print("\nTorch Style")
print(f"\nMin (torch style): {torch.min(tensor)}")
print(f"Max (torch style): {torch.max(tensor)}")
print(f"Sum (torch style): {torch.sum(tensor)}")

Method Style

Min (method style): 0
Max (method style): 90
Sum (method style): 450

Torch Style

Min (torch style): 0
Max (torch style): 90
Sum (torch style): 450


Both styles are equally valid. `tensor.min()` is shorter; `torch.min(tensor)` is more explicit. You'll see both in real code.

**What These Return - Scalar Tensors**

Notice the outputs are single numbers. In PyTorch, that single number is still technically a tensor (a 0-dimension scalar tensor). If you need it as a plain Python number for further use:

In [36]:
# .item() pulls the number out of the tensor wrapper
min_val = tensor.min().item()
max_val = tensor.max().item()

print(f"Min as plain Python number: {min_val}")
print(f"Max as plain Python number: {max_val}")
print(f"Type: {type(min_val)}")

Min as plain Python number: 0
Max as plain Python number: 90
Type: <class 'int'>


Use `.item()` whenever you need to use the result in regular Pyton math outside of PyTorch

<table style="font-family: sans-serif; font-size: 15px; border-collapse: separate; border-spacing: 0; width: 100%; max-width: 860px;">
  <thead>
    <tr style="background-color: #f0f4ff;">
      <th style="padding: 16px 22px; text-align: left; border-bottom: 2px solid #c5d0f5; color: #3a3aaa;">What you want</th>
      <th style="padding: 16px 22px; text-align: left; border-bottom: 2px solid #c5d0f5; color: #3a3aaa;">Code</th>
      <th style="padding: 16px 22px; text-align: left; border-bottom: 2px solid #c5d0f5; color: #3a3aaa;">Watch out for</th>
    </tr>
  </thead>
  <tbody>
    <tr style="background-color: #ffffff;">
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">Smallest value</td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;"><code>tensor.min()</code></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">Returns a scalar tensor — use .item() for plain Python</td>
    </tr>
    <tr style="background-color: #f9f9f9;">
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">Largest value</td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;"><code>tensor.max()</code></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">Returns a scalar tensor — use .item() for plain Python</td>
    </tr>
    <tr style="background-color: #ffffff;">
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">Add all values</td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;"><code>tensor.sum()</code></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">Works on int64 — no conversion needed</td>
    </tr>
    <tr style="background-color: #f9f9f9;">
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">Average of all values</td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;"><code>tensor.type(torch.float32).mean()</code></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">Must convert to float32 first — crashes on int64</td>
    </tr>
    <tr style="background-color: #ffffff;">
      <td style="padding: 18px 22px;">Extract as plain number</td>
      <td style="padding: 18px 22px;"><code>.item()</code></td>
      <td style="padding: 18px 22px;">Needed when using result outside of PyTorch math</td>
    </tr>
  </tbody>
</table>

## Lesson 8: Finding Positions - Where is the Min/Max?

**Why Does Position Matter More Than Value?**

In AI, knowing the *value* of the highlest number is often less useful than knowing *where* it is.

Here's why: when an AI model classifies  a chest X-ray, the output is a tensor of probabilities - one number per possible diagnosis.


In [37]:
# Same tensor as Lesson 7 - a flat list of 10 numbers
tensor = torch.arange(start=0, end=100, step=10)
print(f"Our tensor: {tensor}")

Our tensor: tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])


In [38]:
# ARGMIN - position of the smallest value (0)
print(f"Position of minimum value: {tensor.argmin()}")

# ARGMAX - position of the largest value (90)
print(f"Position of maximum value: {tensor.argmax()}")

Position of minimum value: 0
Position of maximum value: 9


**Verify it makes senses**

In [39]:
# Double-check by using the position to grab the actual value
min_pos = tensor.argmin().item()    # get position as plain Python int
max_pos = tensor.argmax().item()  #  get position as plain Python int

print(f"Min is at position {min_pos} - value there is: {tensor[min_pos]}")
print(f"Max is at postiton {max_pos} - value there is: {tensor[max_pos]}")

Min is at position 0 - value there is: 0
Max is at postiton 9 - value there is: 90


`tensor[position]` is how you grab a specific value using its position - like looking up a locker by its number.

**A More Interesting Example - Unordered Tensor**

The real power shows when the values aren't in order:

In [40]:
# An unordered tensor - like a model's output probabilities
predictions = torch.tensor([0.05, 0.12, 0.91, 0.03, 0.08])

print(f"Predictions tensor: {predictions}")
print(f"Highest confidence at position: {predictions.argmax()}")
print(f"Lowest confidence at positin: {predictions.argmin()}")

Predictions tensor: tensor([0.0500, 0.1200, 0.9100, 0.0300, 0.0800])
Highest confidence at position: 2
Lowest confidence at positin: 3


In [41]:
# Use the position to name the diagnosis
diagnoses = ["flu", "cold", "pmeumonia", "TB", "healthy"]
predicted_class = diagnoses[predictions.argmax().item()]
print(f"Model predicts: {predicted_class}")

Model predicts: pmeumonia


This is literally how every AI classifier works at its core - `argmax` on the output tensor gives yu the predicted class.

**argmin vs min - The Key Difference**

This is the most important distinction in this lesson:

In [42]:
print(f"tensor.min()         =   {tensor.min()}")
print(f"tensor.argmin()    =   {tensor.argmin()}")

print(f"\ntensor.max()        =   {tensor.max()}")
print(f"tensor.argmax()    = {tensor.argmax()}")

tensor.min()         =   0
tensor.argmin()    =   0

tensor.max()        =   90
tensor.argmax()    = 9


In this particular tensor they look similar because the smallest value (0) happens to also be at position 0. But that's a coincidence - with the predictios tensor above the max value was `0.92` but its position was `2`. Value and position are completely different things.

<table style="font-family: sans-serif; font-size: 15px; border-collapse: separate; border-spacing: 0; width: 100%; max-width: 860px;">
  <thead>
    <tr style="background-color: #f0f4ff;">
      <th style="padding: 16px 22px; text-align: left; border-bottom: 2px solid #c5d0f5; color: #3a3aaa;">What you want</th>
      <th style="padding: 16px 22px; text-align: left; border-bottom: 2px solid #c5d0f5; color: #3a3aaa;">Code</th>
      <th style="padding: 16px 22px; text-align: left; border-bottom: 2px solid #c5d0f5; color: #3a3aaa;">Returns</th>
    </tr>
  </thead>
  <tbody>
    <tr style="background-color: #ffffff;">
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">The smallest value</td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;"><code>tensor.min()</code></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">The actual number e.g. 0</td>
    </tr>
    <tr style="background-color: #f9f9f9;">
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">Position of the smallest value</td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;"><code>tensor.argmin()</code></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">The index e.g. 0</td>
    </tr>
    <tr style="background-color: #ffffff;">
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">The largest value</td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;"><code>tensor.max()</code></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">The actual number e.g. 90</td>
    </tr>
    <tr style="background-color: #f9f9f9;">
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">Position of the largest value</td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;"><code>tensor.argmax()</code></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">The index e.g. 9</td>
    </tr>
    <tr style="background-color: #ffffff;">
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">Grab value at a position</td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;"><code>tensor[position]</code></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">The value stored at that index</td>
    </tr>
    <tr style="background-color: #f9f9f9;">
      <td style="padding: 18px 22px;">Extract position as plain Python int</td>
      <td style="padding: 18px 22px;"><code>tensor.argmax().item()</code></td>
      <td style="padding: 18px 22px;">Plain Python int — usable outside PyTorch</td>
    </tr>
  </tbody>
</table>

## Lesson 9: Reshaping & Rearranging Tensors

**Why Would You Ever Need to Reshape?**

The math inside AI models is extremely picky about the shape of tensors coming in. Two tensors might hold the exact same numbers, but if their shapes don't match what the model expects, it crashes.

Reshaping lets you **rearrange the same numbers into a different shape** without changing any of the values. Think of it like moving the same amount of water between containers - the water doesn't change, only the container shape does.

A very common real example: an image is stored as `(224, 224, 3)` but a particular layer inside your model expects `(1, 224, 224, 3)`. Same data, different shape. Reshaping fixes it instantly.

In [43]:
# Create a flat list of 9 numbers to practice reshaping on
x = torch.arange(1., 10.) # the . after 1 and 10 forces float32 instead of int64

print(f"Original tensor: \n{x}")
print(f"\nShape: {x.shape}")
print(f"\nDtype: {x.dtype}")

Original tensor: 
tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

Shape: torch.Size([9])

Dtype: torch.float32


**reshape() - Change the Shape**

In [44]:
# Reshape flat list of 9 into a 3x3 grid
# 9 total numbers - we can rearange into 3 rows x 3 columns
x_reshaped = x.reshape(3, 3)

print(f"Reshaped tensor: \n{x_reshaped}")
print(f"\nNew shape: \n{x_reshaped.shape}")

Reshaped tensor: 
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

New shape: 
torch.Size([3, 3])


PyTorch fills the new shape row by row - 1, 2, 3 go into row 1, then 4, 5, 6 into row 2, and so on.

**The one rule: total numbers must stay the same**

In [45]:
# 9 numbers can become
x.reshape(3, 3)   # 3x3 = 9
x.reshape(1, 9)   # 1x9 = 9
x.reshape(9, 1)   # 9x1 = 9

# But NOT:
# x.reshape(4, 3)   # 4x3 = 12 - you can't create numbers from nothing

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

**view() - Reshape Without Copying**

In [46]:
# view() does the same as reshape but shares the same memory
# Changing the view changes the original - they point to the same data
z = x.view(1, 9)

print(f"View of x:\n{z}")
print(f"Shape: {z.shape}")

View of x:
tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Shape: torch.Size([1, 9])


**reshape vs view - what is the difference?**

In [47]:
# CRITICAL ; view shares memory with the original
# Changing z also changes x - they're the same data, different shape
z[:, 0] = 99    # change first value of z

print(f"z after change: {z}")
print(f"x after change: {x}")

z after change: tensor([[99.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])
x after change: tensor([99.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])


`reshape` is safer - it creates a copy when needed. `view` is faster - no copy, shared memory. In practice, use `reshape` unless you have a specific reason to use `view`.

**stack() - Combine Multiple Tensors Together**

Sometimes you have several separate tensors and you need to combine them into one. `torch.stack` does exactly that.

In [48]:
# Reset x back to original values
x = torch.arange(1., 10.)

# Stack the same tensor 4 times on top of each other (dim=0 means new row)
x_stacked = torch.stack([x, x, x, x], dim=0)

print(f"Stacked tensor:\n{x_stacked}")
print(f"Shape: {x_stacked.shape}")

Stacked tensor:
tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Shape: torch.Size([4, 9])


`dim=0` means "stack along a new first  dimension" - each tensor becomes a new row. This is how you'd batch multiple patient scans together into a single tensor before feeding them into a model.

**squeez() and unsqueezed() - Remove or Add a Dimension**

These two are used constantly when shapes are almost right but have an extra `1` somewhere.

In [49]:
# Reshape x into shape(1, 9) - a grid with 1 row and 9 columns
x_reshaped = x.reshape(1, 9)
print(f"Before squeeze - shape: {x_reshaped.shape}\n")

# squeeze() - removes any dimension that has size 1
x_squeezed = x_reshaped.squeeze()
print(f"After squeeze - shape: {x_squeezed.shape}")
print(f"After squeeze - tensor: {x_squeezed}")

Before squeeze - shape: torch.Size([1, 9])

After squeeze - shape: torch.Size([9])
After squeeze - tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])


`squeeze` collapses the useless 1 dimension - like deflating an empty outer wrapper.

Now the opposite - `unsqueeze` adds a dimension of size 1 at a position you choose:

In [50]:
# unsquuze(dim=0) adds a new dimension at position 0 (the front)
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"After unsquuze(0) - shape: {x_unsqueezed.shape}")

# unsquuze(dim=1) adds a new dimension at position 1 (the middle)
x_unsqueezed_1 = x_squeezed.unsqueeze(dim=1)
print(f"After unsquuze(1) - shape: {x_unsqueezed_1.shape}")

After unsquuze(0) - shape: torch.Size([1, 9])
After unsquuze(1) - shape: torch.Size([9, 1])


Think of `torch.unsqueeze` as wrapping the tensor in a new outer box at the position you specify.

**permute() - Rearrange Dimension Order**

`permute` reorders the dimensions of a tensor. This is especially useful with images, where diffeerent models expect dimensions in different orders.

In [51]:
# Create a fake image tensor: 224 height x 224 width x 3 color channels
image_tensor = torch.rand(size=(224, 224, 3))
print(f"Original image shape: {image_tensor.shape}")

# Some modls expect color channels FIRST : (3, 224, 224) instead of (224, 224, 3)
# permute(2, 0, 1) means: put old dim 2 first, then old dim 0, the old dim 1
image_permuted = image_tensor.permute(2, 0, 1)
print(f"Permuted image shape: {image_permuted.shape}")

Original image shape: torch.Size([224, 224, 3])
Permuted image shape: torch.Size([3, 224, 224])


The value don't change - only the order of dimensions does. `permute` shares memory with the original just like `view`.

<table style="font-family: sans-serif; font-size: 15px; border-collapse: separate; border-spacing: 0; width: 100%; max-width: 900px;">
  <thead>
    <tr style="background-color: #f0f4ff;">
      <th style="padding: 16px 22px; text-align: left; border-bottom: 2px solid #c5d0f5; color: #3a3aaa;">Tool</th>
      <th style="padding: 16px 22px; text-align: left; border-bottom: 2px solid #c5d0f5; color: #3a3aaa;">Code</th>
      <th style="padding: 16px 22px; text-align: left; border-bottom: 2px solid #c5d0f5; color: #3a3aaa;">What it does</th>
      <th style="padding: 16px 22px; text-align: left; border-bottom: 2px solid #c5d0f5; color: #3a3aaa;">Copies data?</th>
    </tr>
  </thead>
  <tbody>
    <tr style="background-color: #ffffff;">
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;"><strong>reshape</strong></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;"><code>x.reshape(3, 3)</code></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">Changes shape, same total numbers</td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">When needed — safer</td>
    </tr>
    <tr style="background-color: #f9f9f9;">
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;"><strong>view</strong></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;"><code>x.view(1, 9)</code></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">Same as reshape, shares memory</td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">Never — faster but risky</td>
    </tr>
    <tr style="background-color: #ffffff;">
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;"><strong>stack</strong></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;"><code>torch.stack([x, x], dim=0)</code></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">Combines multiple tensors into one</td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">Yes — new tensor</td>
    </tr>
    <tr style="background-color: #f9f9f9;">
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;"><strong>squeeze / unsqueeze</strong></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;"><code>x.squeeze() / x.unsqueeze(0)</code></td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">Remove or add a size-1 dimension</td>
      <td style="padding: 18px 22px; border-bottom: 1px solid #eee;">Shares memory</td>
    </tr>
    <tr style="background-color: #ffffff;">
      <td style="padding: 18px 22px;"><strong>permute</strong></td>
      <td style="padding: 18px 22px;"><code>x.permute(2, 0, 1)</code></td>
      <td style="padding: 18px 22px;">Reorders dimension positions</td>
      <td style="padding: 18px 22px;">Shares memory</td>
    </tr>
  </tbody>
</table>

## Lesson 10: PyTorch & NumPy

**What is NumPy and Why Does it Matter?**

Before PyTorch existed, scientists and engineers used a tool called NumPy to do math with arrays of numbers. It became so popular that almost every data science tool in Python — pandas, scikit-learn, matplotlib — stores and exchanges data as NumPy arrays.

This creates a practical problem: your data often arrives as a NumPy array, but PyTorch needs a tensor. And sometimes PyTorch produces a tensor that another tool needs back as a NumPy array.

PyTorch solves this with two simple functions that convert in both directions.

**Direction 1 — NumPy Array → PyTorch Tensor**

In [52]:
# Create a NumPy array - the standard way NumPy makes arrays
array = np.arange(1.0, 8.0)

# Convert NumPy array into a PyTorch tensor
tensor = torch.from_numpy(array)

print(f"NumPy array:    {array}")
print(f"NumPy dtype:    {array.dtype}")

print(f"\nPyTorch tensor:   {tensor}")
print(f"Tensor dtype:        {tensor.dtype}")

NumPy array:    [1. 2. 3. 4. 5. 6. 7.]
NumPy dtype:    float64

PyTorch tensor:   tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)
Tensor dtype:        torch.float64


**Two things to notice here**

**First - the dtype is** `float64`, **not** `float32`. NumPy defaults to 64-bit decimals. PyTorch defaults to 32-bit. `torch.from_numpy` respects NumPy's dtype and carries it across exactly. If you need float32 for your model, convert afterwards:

In [53]:
# Convert to float32 after importing from NumPy
tensor_f32 = torch.from_numpy(array).type(dtype=torch.float32)
print(f"Converted dtype:  {tensor_f32.dtype}")

Converted dtype:  torch.float32


**Second - they share memory**. Just like `view`, `torch.from_numpy` does not copy the data. The tensor and the array point to the same memory:

In [54]:
# Changing the NumPy array also changes the tensor
array[0] = 99
print(f"NumPy array after change:   {array}")
print(f"PyTorch tensor after change:  {tensor}")

NumPy array after change:   [99.  2.  3.  4.  5.  6.  7.]
PyTorch tensor after change:  tensor([99.,  2.,  3.,  4.,  5.,  6.,  7.], dtype=torch.float64)


If you don't want this shared memory behavior, make a copy immediately:

In [55]:
# .copy() breaks the memry link - now they're independent
tensor_independent = torch.from_numpy(array.copy())
print(tensor_independent)

tensor([99.,  2.,  3.,  4.,  5.,  6.,  7.], dtype=torch.float64)


**Direction 2 - PyTorch Tensor -> NumPy Array

In [56]:
# Start with a PyTorch tensor
tensor = torch.ones(7)

# Convert PyTorch tensor into a NumPy array
numpy_array = tensor.numpy()

print(f"PyTorch tensor:   {tensor}")
print(f"Tensor dtype:       {tensor.dtype}")

print(f"\nNumPy array:     {numpy_array}")
print(f"NumPy dtype:        {numpy_array.dtype}")

PyTorch tensor:   tensor([1., 1., 1., 1., 1., 1., 1.])
Tensor dtype:       torch.float32

NumPy array:     [1. 1. 1. 1. 1. 1. 1.]
NumPy dtype:        float32


This direction also shares memory - changing the tensor changes the array and vice versa.